plant_database = [
    {
        'plant_name': 'Tomato',
        'optimal_temperature': (20, 30),
        'optimal_precipitation': (600, 800),
        'optimal_solar_radiation': (180, 250),
        'optimal_humidity': (60, 80),
        'optimal_wind_speed': (3, 10),
        'optimal_soil_moisture': (0.25, 0.4),
        'optimal_clay_content': (15, 25),
        'optimal_sand_content': (20, 35),
        'optimal_silt_content': (30, 50),
        'optimal_soil_ph': (5.5, 7.0),
        'optimal_soil_organic_carbon': (2.0, 4.0)
    },
    {
        'plant_name': 'Wheat',
        'optimal_temperature': (12, 25),
        'optimal_precipitation': (400, 600),
        'optimal_solar_radiation': (150, 200),
        'optimal_humidity': (50, 70),
        'optimal_wind_speed': (2, 8),
        'optimal_soil_moisture': (0.2, 0.3),
        'optimal_clay_content': (10, 30),
        'optimal_sand_content': (20, 40),
        'optimal_silt_content': (25, 45),
        'optimal_soil_ph': (6.0, 7.5),
        'optimal_soil_organic_carbon': (1.5, 3.0)
    },
    {
        'plant_name': 'Rice',
        'optimal_temperature': (25, 35),
        'optimal_precipitation': (1000, 1500),
        'optimal_solar_radiation': (200, 250),
        'optimal_humidity': (70, 90),
        'optimal_wind_speed': (1, 5),
        'optimal_soil_moisture': (0.3, 0.5),
        'optimal_clay_content': (20, 40),
        'optimal_sand_content': (15, 30),
        'optimal_silt_content': (40, 60),
        'optimal_soil_ph': (5.0, 6.5),
        'optimal_soil_organic_carbon': (3.0, 5.0)
    },
    {
        'plant_name': 'Maize',
        'optimal_temperature': (18, 27),
        'optimal_precipitation': (500, 700),
        'optimal_solar_radiation': (180, 230),
        'optimal_humidity': (60, 75),
        'optimal_wind_speed': (2, 7),
        'optimal_soil_moisture': (0.25, 0.4),
        'optimal_clay_content': (15, 30),
        'optimal_sand_content': (20, 35),
        'optimal_silt_content': (30, 50),
        'optimal_soil_ph': (5.5, 7.0),
        'optimal_soil_organic_carbon': (2.0, 4.0)
    },
    {
        'plant_name': 'Soybean',
        'optimal_temperature': (20, 30),
        'optimal_precipitation': (600, 800),
        'optimal_solar_radiation': (180, 250),
        'optimal_humidity': (60, 80),
        'optimal_wind_speed': (2, 8),
        'optimal_soil_moisture': (0.25, 0.4),
        'optimal_clay_content': (15, 25),
        'optimal_sand_content': (20, 35),
        'optimal_silt_content': (30, 50),
        'optimal_soil_ph': (5.8, 7.5),
        'optimal_soil_organic_carbon': (2.0, 3.5)
    },
    {
        'plant_name': 'Cotton',
        'optimal_temperature': (25, 35),
        'optimal_precipitation': (400, 600),
        'optimal_solar_radiation': (200, 250),
        'optimal_humidity': (50, 70),
        'optimal_wind_speed': (2, 10),
        'optimal_soil_moisture': (0.2, 0.35),
        'optimal_clay_content': (10, 30),
        'optimal_sand_content': (20, 40),
        'optimal_silt_content': (25, 45),
        'optimal_soil_ph': (5.5, 7.0),
        'optimal_soil_organic_carbon': (1.5, 3.0)
    }
]
